---
title: "Assignment 1: Introduction"
author: "Elizabeth Miles-Flynn"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: This is my first time using Git. In my ecology undergraduate classes, I would copy/paste R code from my professors to analyze our field data with ANOVA, uploading excel tables, and editing graphs to fit our lab report needs. I don't have any Python or formal coding experience.

2. Are there any components of the course about which you feel confident?

> Answer: I feel comfortable with looking at online sources to help with troubleshooting issues. Especially if there are any errors in my code, I usually copy/paste the script and ask google search engine what steps or lines I should fix.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I want to refamiliarize myself with coding language. The only ones I remember is that ">" is for writing code lines and then "#" is to help with notes that will not be coded. Overall, I want to be confident with experimenting with R Studio and write my own code from scratch that will be relevant to the modelling outcomes to address project concerns.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/emilesflynn/EDE_Fall2025

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
